### ISSUE TITLE
code

### ISSUE THREAD

**Issue by zhanlingm** [ARUP-NGS/jenever#2]
Hello, Professor! I am very interested in reading your article, but I have some questions about the details of the code. When I run generate_bed_labels.sh, I find that GRCh37_AllTandemRepeatsandHomopolymers_slop5.bed.gz and GRCh37_allallowmapandsegdupregions.bed.gz are not downloaded in download_giab.sh. What are these two files? Is there a download link?

**Comment by brendanarup** [comment]
Hi there, all of those stratification BED files can be found here: https://github.com/genome-in-a-bottle/genome-stratifications, but they're only needed if you're going to train your own model and want to generate your own labelled region BED files to create training data.  If you're doing that,  you can use whatever region-labeling scheme you'd like, but I've found that labeling (and greatly upsampling) any regions that overlap the "AllTandemRepeatsAndHomopolymers" file really helps improve performance. Let me know how it goes!

Sorry, correction here - that repo contains the *code* for generating the stratification files. The actual files are hosted here: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.5/

**Comment by zhanlingm** [comment]
Thank you very much! My problem has been solved.

> Hi there, all of those stratification BED files can be found here: https://github.com/genome-in-a-bottle/genome-stratifications, but they're only needed if you're going to train your own model and want to generate your own labelled region BED files to create training data. If you're doing that, you can use whatever region-labeling scheme you'd like, but I've found that labeling (and greatly upsampling) any regions that overlap the "AllTandemRepeatsAndHomopolymers" file really helps improve performance. Let me know how it goes!您好，所有这些分层 BED 文件都可以在这里找到：https://github.com/genome-in-a-bottle/genome-stratifications，但只有当您要训练自己的模型并希望生成自己的标记区域 BED 文件来创建训练数据时，才需要它们。如果您正在这样做，您可以使用任何您想要的区域标记方案，但我发现标记（并大大上采样）与 “AllTandemRepeatsAndHomopolymers” 文件重叠的任何区域确实有助于提高性能。让我知道进展如何！
> 
> Sorry, correction here - that repo contains the _code_ for generating the stratification files. The actual files are hosted here: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.5/抱歉，此处更正 - 该存储库包含用于生成分层文件_的代码_。实际文件托管在此处：https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.5/

**Comment by zhanlingm** [comment]
Thank you very much! My problem has been solved.
